version: "3.4"

services: 
  apicifra:
    container_name: finoban-api-cifra
    image: finoban-api-cifra
    environment: 
      - PORT=8080
    ports: 
      - 8080:8080
    build: 
      context: .
      dockerfile: Dockerfile