```{r}
cpf_dig_controle <- function(y){
 v1 <- 0L
  v2 <- 0L
  num <- is.numeric(y)
  z <- as.integer(strsplit(as.character(y), "")[[1]])
  n <- length(z)
  if(num){
    if(n == 7){
      z <- c(0, z, sample(0:9, 1))
    } else{
      if(n == 8){
        z <- c(0, z)
      } else{
        z <- z
      }
    }
  } else{
    if(n == 8){
      z <- c(z, sample(0:9, 1))
    } else{
      z <- z
    }
  }
  for(i in seq_along(z)){
    v1 <- v1 + z[i]*(11-i)
    v2 <- v2 + z[i]*(12-i)
  }
  v1 <- v1 %% 11
  if(v1 < 2){
    v1 <- 0
  } else{
    v1 <- 11 - v1
  }
  v2 <- v2 + 2*v1
  v2 <- v2 %% 11
  if(v2 < 2){
    v2 <- 0
  } else{
    v2 <- 11 - v2
  }
  c(v1, v2)
}

cpf_gerar <- function(x){
   g <- function(y, v){
     num <- is.numeric(y)
     z <- as.integer(strsplit(as.character(y), "")[[1]])
     n <- length(z)
     if(num){
       if(n == 7){
         z <- c(0, z, sample(0:9, 1))
       } else{
         if(n == 8){
           z <- c(0, z)
         } else{
           z <- z
         }
       }
     } else{
       if(n == 8){
         z <- c(z, sample(0:9, 1))
       } else{
         z <- z
       }
     }
     z <- as.integer(c(z, v))
     res <- sprintf(fmt = "%d%d%d.%d%d%d.%d%d%d-%d%d",
                    z[1], z[2], z[3], z[4], z[5], z[6], z[7], z[8], z[9], z[10], z[11])
     res
   }
   v <- lapply(x, cpf_dig_controle)
   result <- sapply(seq_along(x), function(i) g(x[i], v[[i]]))
   result
}

cpf_validar <- function(x){
  f <- function(y){
    z <- unlist(strsplit(y, "\\."))
    v <- substr(z[3], 5, 6)
    v <- as.integer(unlist(strsplit(v, "")))
    z[3] <- substr(z[3], 1, 3)
    z <- as.integer(paste(z, collapse = ""))
    list(x = z, v = v)
  }
  result <- lapply(x, f)
  valido <- lapply(result, function(r) unlist(lapply(r$x, cpf_dig_controle)))
  valido <- sapply(seq_along(valido), function(i)
    result[[i]]$v[1] == valido[[i]][1] & result[[i]]$v[2] == valido[[i]][2]
  )
  valido
}
```

```{r}
set.seed(123)
idade <-round(rnorm(n,40,5))
idade
```

```{r}
set.seed(123)
tempoFinanciamento <-round(rnorm(n,25,5))
tempoFinanciamento
```


```{r}
set.seed(123)
regiao <- round(runif(n,1,6))
regiao.r <-factor(regiao,
                  levels = c(1,2,3,4,5,6),
                  labels = c("centro","consolação","brooklin",
                             "mooca","santo-amaro","interlagos")
                  )
regiao.r
```

```{r}
set.seed(123)
valorImovel <- round(rnorm(n,100000,25000),2)
valorImovel
```

```{r}
set.seed(123)
renda <- round(rnorm(n,6000,1000),2)
renda
```

```{r}
set.seed(123)
banco <- round(runif(n,1,3))
banco.r <- factor(banco,
                  levels= c(1,2,3),
                  labels = c("Banco do Presil","S16 Bank","Banco Cifra")
                  ) 
banco.r
```

```{r}
set.seed(123)
avaliacao <-round(runif(n,1,3))
avaliacao.r <- factor(avaliacao,
                    levels = c(0,1,2),
                    labels = c("positiva","negativa","n/ avaliado")
                    )
avaliacao.r
```

```{r}
#Calculo para % de renda
`%rendaFinanciamento` <- c()
for(i in 1:n){
  `%rendaFinanciamento`[i] <- 
    round(((valorImovel[i]/(tempoFinanciamento[i]*12))*100/renda[i]),2)
}
`%rendaFinanciamento`

```


```{r}
df <- data.frame(idade,regiao.r,valorImovel,renda,tempoFinanciamento,`%rendaFinanciamento`, banco.r,avaliacao.r, dataHoraEntrada, dataHoraSaida)

df
```


```{r}
head(table(valorImovel))

 
head(idade)

barplot(table(avaliacao.r),
        col=c("#972838", "#278284"),
        main = "Avaliação")

```


```{r}
set.seed(123)
varianciaTempoAcesso <-round(rnorm(n,180,120))
dataHoraEntrada <- c()
dataHoraSaida <- c()
now <- Sys.time()
now
for(i in 1:n){
  dataHoraEntrada[i] <- as.character(now)
  dataHoraSaida[i] <- as.character(now + varianciaTempoAcesso[i])
}
varianciaTempoAcesso
dataHoraEntrada
dataHoraSaida

```

