```{r}
cpf_dig_controle <- function(y){
 v1 <- 0L
  v2 <- 0L
  num <- is.numeric(y)
  z <- as.integer(strsplit(as.character(y), "")[[1]])
  n <- length(z)
  if(num){
    if(n == 7){
      z <- c(0, z, sample(0:9, 1))
    } else{
      if(n == 8){
        z <- c(0, z)
      } else{
        z <- z
      }
    }
  } else{
    if(n == 8){
      z <- c(z, sample(0:9, 1))
    } else{
      z <- z
    }
  }
  for(i in seq_along(z)){
    v1 <- v1 + z[i]*(11-i)
    v2 <- v2 + z[i]*(12-i)
  }
  v1 <- v1 %% 11
  if(v1 < 2){
    v1 <- 0
  } else{
    v1 <- 11 - v1
  }
  v2 <- v2 + 2*v1
  v2 <- v2 %% 11
  if(v2 < 2){
    v2 <- 0
  } else{
    v2 <- 11 - v2
  }
  c(v1, v2)
}

cpf_gerar <- function(x){
   g <- function(y, v){
     num <- is.numeric(y)
     z <- as.integer(strsplit(as.character(y), "")[[1]])
     n <- length(z)
     if(num){
       if(n == 7){
         z <- c(0, z, sample(0:9, 1))
       } else{
         if(n == 8){
           z <- c(0, z)
         } else{
           z <- z
         }
       }
     } else{
       if(n == 8){
         z <- c(z, sample(0:9, 1))
       } else{
         z <- z
       }
     }
     z <- as.integer(c(z, v))
     res <- sprintf(fmt = "%d%d%d.%d%d%d.%d%d%d-%d%d",
                    z[1], z[2], z[3], z[4], z[5], z[6], z[7], z[8], z[9], z[10], z[11])
     res
   }
   v <- lapply(x, cpf_dig_controle)
   result <- sapply(seq_along(x), function(i) g(x[i], v[[i]]))
   result
}

cpf_validar <- function(x){
  f <- function(y){
    z <- unlist(strsplit(y, "\\."))
    v <- substr(z[3], 5, 6)
    v <- as.integer(unlist(strsplit(v, "")))
    z[3] <- substr(z[3], 1, 3)
    z <- as.integer(paste(z, collapse = ""))
    list(x = z, v = v)
  }
  result <- lapply(x, f)
  valido <- lapply(result, function(r) unlist(lapply(r$x, cpf_dig_controle)))
  valido <- sapply(seq_along(valido), function(i)
    result[[i]]$v[1] == valido[[i]][1] & result[[i]]$v[2] == valido[[i]][2]
  )
  valido
}
```

```{r}
fa <- function(x) iconv(x, to = "ASCII//TRANSLIT")
```


```{r}
rm_accent <- function(str,pattern="all") {
  # Rotinas e funções úteis V 1.0
  # rm.accent - REMOVE ACENTOS DE PALAVRAS
  # Função que tira todos os acentos e pontuações de um vetor de strings.
  # Parâmetros:
  # str - vetor de strings que terão seus acentos retirados.
  # patterns - vetor de strings com um ou mais elementos indicando quais acentos deverão ser retirados.
  #            Para indicar quais acentos deverão ser retirados, um vetor com os símbolos deverão ser passados.
  #            Exemplo: pattern = c("´", "^") retirará os acentos agudos e circunflexos apenas.
  #            Outras palavras aceitas: "all" (retira todos os acentos, que são "´", "`", "^", "~", "¨", "ç")
  if(!is.character(str))
    str <- as.character(str)

  pattern <- unique(pattern)

  if(any(pattern=="Ç"))
    pattern[pattern=="Ç"] <- "ç"

  symbols <- c(
    acute = "áéíóúÁÉÍÓÚýÝ",
    grave = "àèìòùÀÈÌÒÙ",
    circunflex = "âêîôûÂÊÎÔÛ",
    tilde = "ãõÃÕñÑ",
    umlaut = "äëïöüÄËÏÖÜÿ",
    cedil = "çÇ"
  )

  nudeSymbols <- c(
    acute = "aeiouAEIOUyY",
    grave = "aeiouAEIOU",
    circunflex = "aeiouAEIOU",
    tilde = "aoAOnN",
    umlaut = "aeiouAEIOUy",
    cedil = "cC"
  )

  accentTypes <- c("´","`","^","~","¨","ç")

  if(any(c("all","al","a","todos","t","to","tod","todo")%in%pattern)) # opcao retirar todos
    return(chartr(paste(symbols, collapse=""), paste(nudeSymbols, collapse=""), str))

  for(i in which(accentTypes%in%pattern))
    str <- chartr(symbols[i],nudeSymbols[i], str)

  return(str)
}
```


```{r}
set.seed(123)
dataNasc <-sample(seq(as.Date('1970/01/01'), as.Date('2000/01/01'), by="day"), n)
dataNasc

```

```{r}
set.seed(123)
tempoFinanciamento <-round(rnorm(n,25,5))
tempoFinanciamento
```


```{r}
set.seed(123)
regiao <- round(runif(n,1,6))
regiao.r <-factor(regiao,
                  levels = c(1,2,3,4,5,6),
                  labels = c("centro","consolação","brooklin",
                             "mooca","santo-amaro","interlagos")
                  )
regiao.r
```

```{r}
set.seed(124)
valorImovel <- round(rnorm(n,100000,25000),2)
#valorImovel
```

```{r}
set.seed(125)
renda <- round(rnorm(n,5000,1000),2)
renda
```

```{r}
set.seed(123)
bancoEscolhido <- round(runif(n,1,3))
banco.r <- factor(bancoEscolhido,
                  levels= c(1,2,3),
                  labels = c("Banco do Presil","S16 Bank","Banco Cifra")
                  ) 
banco.r
```

```{r}
set.seed(129)
avaliacao <-round(rnorm(n,1,1))
avaliacao.r <- factor(avaliacao,
                    levels = c(1,2,3),
                    labels = c("negativa","positiva","n/ avaliado")
                    )
avaliacao.r
plot( as.factor( avaliacao.r )) 
```

```{r}
#Calculo para % de renda
porcentagemRenda <- c()
for(i in 1:n){
  porcentagemRenda[i] <- 
    round(((valorImovel[i]/(tempoFinanciamento[i]*12))*100/renda[i]),0)
}
porcentagemRenda

```


```{r}
set.seed(123)
varianciaTempoAcesso <-round(rnorm(n,4*60,120))
varianciaTempoAvaliacao <-round(rnorm(n,60,30))
dataHoraEntrada <- c()
dataHoraSaida <- c()
dataHoraAvaliacao <- c()
now <- Sys.time()
for(i in 1:n){
  dataHoraEntrada[i] <- as.character(now)
  dataHoraSaida[i] <- as.character(now + varianciaTempoAcesso[i])
  dataHoraAvaliacao[i] <- as.character((now + varianciaTempoAcesso[i]) -    varianciaTempoAvaliacao[i])
}
varianciaTempoAcesso
dataHoraEntrada
dataHoraSaida
dataHoraAvaliacao

```

```{r}
set.seed(123)
paginaSaida <-round(runif(n,1,5))
paginaSaida.r <- factor(paginaSaida,
                        levels = c(1,2,3,4,5),
                        labels = c("dash","hub","cadastro","login","home")
)
paginaSaida.r
plot( as.factor( paginaSaida.r )) 
```

```{r}

set.seed(123)
paginaSaida <-round(runif(n,1,5))
statusSaida <- factor(paginaSaida,
                        levels = c(1,2,3,4,5),
                        labels = c(1,0,0,0,0)
)
paginaSaida
statusSaida
plot( as.factor( statusSaida )) 


```

```{r}
set.seed(123)
#paginaSaida <-round(runif(n,1,5))
#statusSaida <- factor(paginaSaida,
#                        levels = c(1,2,3,4,5),
##                        labels = c("100%","80%","60%","40%","20%")
#)
#statusSaida
#plot( as.factor( statusSaida )) 
```

```{r}
set.seed(123)
varianciaTempoAcesso <-round(rnorm(n,4*60,120))

tempoAcesso <- c()
for(i in 1:n){
  if(varianciaTempoAcesso[i] >0){
    tempoAcesso[i] <- varianciaTempoAcesso[i]
  }
}

tempoAcesso

```

```{r}
id <- c(1:n)
df <- data.frame(id,idade,regiao.r,valorImovel,renda,tempoFinanciamento,`%rendaFinanciamento`, banco.r,avaliacao.r, dataHoraEntrada, dataHoraSaida, dataHoraAvaliacao,tempoAcesso,paginaSaida.r,statusSaida,paginaSaida)

df
#Mude o caminho para salvar de acordo com sua máquina
#write.csv(df, file = "C:/Users/VINIBAS/Desktop/Finoban/data_science/dataframeFinoban.csv", row.names = #FALSE)
```

```{r}
set.seed(123)
#fkCliente
fkCliente <- c(1:n)
```

```{r}
set.seed(123)
#fkRegiao
fkRegiao <- c(round(runif(n,2448,2453),0))
fkRegiao
```


```{r}
# DATAFRAME DA TABELA ACESSO ACESSO
set.seed(123)
idEntrada <- c(1:n)

dfAcesso <- data.frame(idEntrada,dataHoraEntrada, dataHoraSaida, statusSaida, paginaSaida, statusSaida, paginaSaida, renda, valorImovel, tempoFinanciamento, porcentagemRenda, bancoEscolhido, fkCliente, fkRegiao)
dfAcesso

#write.csv(dfAcesso, file #="C:/Users/VINIBAS/Desktop/Finoban/data_science/dataframeAcesso.csv",
#row.names = FALSE)
```

```{r}
set.seed(123)
id_cliente <-c(1:n)

dfcliente <-data.frame(id_cliente,data_nasc)

dfAvaliacao



write.csv(dfcliente, file ="C:\\Users\\catarina\\Desktop\\Finoban\\data_science\\dfClientee.csv",
row.names = FALSE)


```

```{r}
##AVALIAÇÃO DO SITE

head(table(valorImovel))


barplot(table(valorImovel,renda),
        col=c("#972838", "#278284"),
        main = "Avaliação")

```

```{r}
write.table(df,"C:\\Users\\catarina\\Desktop\\Finoban\\data_science\\teste.csv", row.names = FALSE)
```

```{r}
##REGIÕES ESCOLHIDAS

barplot(table(regiao.r),
        col=c("#972838", "#278284","#364837","#274698","#987573","#873520"),
        main = "Avaliação")

```

```{r}
##TEMPO DE PERMANENCIA


tempoAcesso.r <- round((tempoAcesso/60),1)

barplot(table (tempoAcesso.r))

```


```{r}
##TERMINAR

plot(valorImovel,idade,
     main = "Diagrama de Dispersão",
     xlab = "valor do imovel",
     ylab = "renda",
     pch = 20,
     col = "blue")

```


```{r}
plot(valorImovel,idade,
     main = "Diagrama de Dispersão",
     xlab = "valor do imovel",
     ylab = "idade",
     pch = 20,
     col = "blue")
```


```{r}
#PAGINA DE SAIDA
library("tm")
library("SnowballC")
library("wordcloud")
library("RColorBrewer")

#PARA CSV
text <- read.csv(file.path("C:\\Users\\Admin\\Desktop\\Finoban\\data_science\\dataframeFinoban.csv"), header=TRUE)

objSaida <- Corpus(VectorSource(text$paginaSaida.r))

dtm <- TermDocumentMatrix(objSaida)
m <- as.matrix(dtm)
v <- sort(rowSums(m),decreasing=TRUE)
d <- data.frame(word = names(v),freq=v)

png("C:\\Users\\Admin\\Desktop\\Finoban\\data_science\\paginaSaidaPlot.png", width = 3000, height = 3000,units="px",res=400, bg="white")

barplot(d[1:10,]$freq, las = 2, names.arg = d[1:10,]$word,
        col ="lightblue", main ="Páginas de saida mais frequêntes",
        ylab = "Frequência")

dev.off()
```


```{r}
#WORD CLOUD FEEDBACK
# Install
#install.packages("tm")  # for text mining
#install.packages("SnowballC") # for text stemming
#install.packages("wordcloud") # word-cloud generator 
#install.packages("RColorBrewer") # color palettes
#install.packages("stringr")

# CARREGAR LIBS
library("tm")
library("SnowballC")
library("wordcloud")
library("RColorBrewer")
library("stringr")

#PARA TXT
text <- readLines("C:\\Users\\Admin\\Desktop\\Finoban\\data_science\\teste.txt")

docs <- Corpus(VectorSource(text))

#PARA CSV
#text <- read.csv(file.path("C:\\Users\\Admin\\Desktop\\Finoban\\data_science\#\dataframeFinoban.csv"), header=TRUE)

#docs <- Corpus(VectorSource(text$regiao.r))

inspect(docs)

#LIMPANDO O ARQUIVO
semAcento <- content_transformer(function (x , pattern ) gsub(pattern, "consolacao", x))
docs <- tm_map(docs, semAcento, "consolação")
docs <- tm_map(docs, content_transformer(tolower))
docs <- tm_map(docs, removeNumbers)
docs <- tm_map(docs, removeWords, stopwords("en"))
docs <- tm_map(docs, removePunctuation)

dtm <- TermDocumentMatrix(docs)
m <- as.matrix(dtm)
v <- sort(rowSums(m),decreasing=TRUE)
d <- data.frame(word = names(v),freq=v)
head(d, 10)

barplot(d[1:10,]$freq, las = 2, names.arg = d[1:10,]$word,
        col ="lightblue", main ="Most frequent words",
        ylab = "Word frequencies")

set.seed(1234)
dev.new(width = 1000, height = 1000, unit = "px")

wordcloud(words = d$word, freq = d$freq, min.freq = 1,
          max.words=200, random.order=FALSE, rot.per=0.35, 
          colors=brewer.pal(8, "Dark2"))
```


```{r}
library(tm)
#PARA CSV
text <- read.csv(file.path("C:\\Users\\Admin\\Desktop\\Finoban\\data_science\\feedback.csv"), header=TRUE)

str(words)

fa <- function(x) iconv(x, to = "ASCII//TRANSLIT")

docs <- Corpus(VectorSource(text$oQuePoderiaMelhorar))

docsSemAcento <- fa(docs)

docsSemAcento

#inspect(docsSemAcento)
```



```{r}
library("tm")

#Avaliação do Finoban por Usuarios
text <- read.csv(file.path("C:\\Users\\Admin\\Desktop\\Finoban\\data_science\\gosta_web_sites.csv"), header=TRUE)

docs <- Corpus(VectorSource(text$opiniaoWebSites))

docsSemAcento <- rm_accent(docs)

dtm <- TermDocumentMatrix(docs)
m <- as.matrix(dtm)
v <- sort(rowSums(m),decreasing=TRUE)
d <- data.frame(word = names(v),freq=v)
head(d, 10)

png("C:\\Users\\Admin\\Desktop\\Finoban\\data_science\\avaliacaoPlot.png", width = 3000, height = 3000,units="px",res=400, bg="white")

barplot(d[1:10,]$freq, las = 2, names.arg = d[1:10,]$word, horiz=TRUE,
        col ="lightblue", main ="Gostou do nosso serviço?",
        ylab = "Quantidade de avaliações")

dev.off()
```